"""add playerid to event

Revision ID: 19b99833f494
Revises: 3066834ccddf
Create Date: 2022-03-29 16:11:59.419365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19b99833f494'
down_revision = '3066834ccddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('player_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_event_player_id_player'), 'player', ['player_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_event_player_id_player'), type_='foreignkey')
        batch_op.drop_column('player_id')

    # ### end Alembic commands ###
