"""add pitchzone field to event

Revision ID: 4f26ae246f2f
Revises: ca7cbf77168f
Create Date: 2022-02-09 13:20:25.288936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f26ae246f2f'
down_revision = '45345efebe1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pitchzone', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('pitchzone')

    # ### end Alembic commands ###
