"""add home and away teams to game model

Revision ID: 80906fc5ad07
Revises: 8e748614e4ec
Create Date: 2022-02-16 13:46:00.171797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80906fc5ad07'
down_revision = '4f26ae246f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.add_column(sa.Column('away_team_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('home_team_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_game_home_team_id_team'), 'team', ['home_team_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_game_away_team_id_team'), 'team', ['away_team_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_game_away_team_id_team'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_game_home_team_id_team'), type_='foreignkey')
        batch_op.drop_column('home_team_id')
        batch_op.drop_column('away_team_id')

    # ### end Alembic commands ###
