"""empty message

Revision ID: 8590a8b22368
Revises: b5d3c87265fb
Create Date: 2022-03-28 14:02:11.371766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8590a8b22368'
down_revision = 'b5d3c87265fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint('fk_player_team_id_team', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_player_team_id_team'), 'team', ['team_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_player_team_id_team'), type_='foreignkey')
        batch_op.create_foreign_key('fk_player_team_id_team', 'team', ['team_id'], ['id'])

    # ### end Alembic commands ###
